name: Docker Image CI Order

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build -f ./Services/OrderServiceApp/Dockerfile   --tag order:$(date +%s) .
