name: Docker Image CI Api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build -f ./Services/AggregateGateway/Dockerfile   --tag api:$(date +%s) .
    
    - name: Push to Docker hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ Secrets.DOCKER_USERNAME }}
        password: ${{ Secrets.DOCKER_PASSWORD}}
        repository: Customers-microservice/Services/AggregateGateway
        tags: api:$(date +%s)
