name: Deploy  to Liara

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: deploay-orderapp-to-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli
          liara deploy --api-token="$LIARA_TOKEN" --region iran --detach --app order --port 10043 --image devsali/orderserviceapp
      - name: deploay-customerapp-to-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli
          liara deploy --api-token="$LIARA_TOKEN" --region iran --detach --app customer --port 10042 --image devsali/customerserviceapp
      - name: deploay-api-to-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli
          liara deploy --api-token="$LIARA_TOKEN" --region iran --detach --app customer-service --port 5000 --image devsali/aggregategateway


      - name: deploay-kafka-server-to-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli
          liara deploy --api-token="$LIARA_TOKEN" --region iran --detach --app zookeeper-server --port 2181 --image bitnami/zookeeper:latest
      

      - name: deploay-kafdrop-to-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli
          liara deploy --api-token="$LIARA_TOKEN" --region iran --detach --app kafdrop --port 9000 --image obsidiandynamics/kafdrop

     

      - name: deploay-kafka-server-to-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli
          liara deploy --api-token="$LIARA_TOKEN" --region iran --detach --app kafka-server --port 9092 --image bitnami/kafka:latest

      - name: deploay-eventstore.db-to-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli
          liara deploy --api-token="$LIARA_TOKEN" --region iran --detach --app eventstore.db --port 2113 --image eventstore/eventstore:20.10.2-buster-slimt       


